### ISSUE TITLE
app.digitallinguistics.io appears blank; same with dist branch pulled & deployed locally

### ISSUE THREAD

**Issue by d8vid** [digitallinguistics/app#116]
## Description

https://app.digitallinguistics.io appears mostly blank.

"Lotus" blue header w/icon appears, and below on white background "NavMainSidebarStatus" (the text-only, no active links, concatenated like that).

Same results locally, with forked & pulled 'dist' branch.

## System

**Desktop**
- Linux (Firefox & Chrome)
- Windows (Edge)

**Comment by dwhieb** [comment]
Hi @d8vid - The app is still just in the early phases of development, so there's nothing to see yet. But keep watching this repo in the coming months!
