### ISSUE TITLE
add a Help Menu

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#126]
The app should include an easy way for users to request a feature or report a problem. A link to the GitHub issues page is probably sufficient for now.

- [x] use `rel=help` on the link
- [x] make sure the Lotus icon stays centered in the middle of the banner

**Comment by dwhieb** [comment]
@vadekh Do you want to take this one?

For the time being, I think we can keep this pretty simple: a white link on the right edge of the banner that says "Report an Issue / Request a Feature".

**Comment by dwhieb** [comment]
Now that I've enabled [GitHub Discussions](https://github.com/digitallinguistics/app/discussions) for this repo, I think we should expand this component into a little help menu:

- [x] text in the banner that says "Help & Feedback" with an info icon
- [x] the "Help & Feedback" text should be vertically aligned in the middle of the banner
- [x] clicking the text (might be a button, or a details/summary, or a nav—not sure yet, and we should make sure whatever we choose is both accessible and keyboard navigable) should open a popup menu, similar to GitHub's popup menus:
  ![image](https://user-images.githubusercontent.com/5892997/135515546-90a50e75-eadf-4a05-abf4-3997ecd9bd1b.png)
- [x] contents of the popup menu:
  - [x] What's new [link to Discussions > Announcements forum]
  - [x] Report an issue [opens a bug issue]
  - [x] Request a feature [opens a feature issue]
  - [x] Visit the Q&A [link to Discussions > Q&A]
- [x] Each of the links should have black & white icon before it (will post icons to use here soon)
- [ ] All of these will have the external link style.
- [ ] On narrow screens (maybe smaller than 30em?), the menu should be full width rather than a popup. (Play with GitHub.com's main menu on a small screen to get a sense for what this would look like.)

Overall I think the HTML structure will be pretty similar to the main nav. The styling will just be a little different.

I think this merits its own Help Menu component under `App/`, and can be included in `index.hbs` with `{{> HelpMenu }}`. So this should get its own story too, which should make it easier to develop in isolation.

You don't have to worry about the little notch at the top. The border styles can follow the same border styles as other elements in the app, and should use the `--box-shadow` variable too.

**Comment by vadekh** [comment]
@dwhieb sounds good! I'll start working on this.

**Comment by dwhieb** [comment]
Here are the icons to use:

* [info](https://feathericons.com/?query=info): for "Help & Feedback"
* [megaphone](https://primer.style/octicons/megaphone-24): for "What's new"
* [alert-circle](https://feathericons.com/?query=alert-circle): for "Report an issue"
* [plus-circle](https://feathericons.com/?query=plus-circle): for "Request a feature"
* [help-circle](https://feathericons.com/?query=help): for "Visit the Q&A"

Save the SVG versions of each of these in `src/images` with the names above, and once the app builds they'll be available for you to use as SVG symbols like so:

```html
<svg>
  <use href=#info></use>
</svg>
```

**Comment by dwhieb** [comment]
After a little research, it seems like using `<summary>` and `<details>` might be a great way to handle the expand/collapse functionality. [That's what GitHub did for their menu.](https://css-tricks.com/using-details-for-menus-and-dialogs-is-an-interesting-idea/)

If we can, we should avoid using JavaScript for this component, and I think the summary/details would allow us to do that.

**Comment by dwhieb** [comment]
[You noted](https://github.com/digitallinguistics/app/pull/293#issue-746840064) that on small screen sizes the text overlaps with other elements. To address this let's hide the "Help & Feedback" text on small screens and just show the icon. Use the `.visually-hidden` class for this so that the text is still accessible to screen readers.

**Comment by vadekh** [comment]
The `#info` image name had to be changed to avoid conflict with the HTML ARIA element, so it is called `iicon.svg`
