### ISSUE TITLE
List story should use the List view

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#168]
The List story should use an actual List view, as a mini test of its functionality.

Maybe just replace the Cypress tests for this component with a story.

**Comment by vadekh** [comment]
@dwhieb looks like you handled this on some other branch, the code on `main` now uses `ListView`, so I am going to close this.

**Comment by dwhieb** [comment]
@vadekh thanks! FYI you can track down what commit a change was made in with using [file history and blaming](https://docs.github.com/en/repositories/working-with-files/using-files/tracking-changes-in-a-file).

https://github.com/digitallinguistics/app/blame/main/src/components/List/List.stories.js

**Comment by dwhieb** [comment]
Closed by 15e5afb817a5bdaeb67eb23671f47155648ddea1.
