### ISSUE TITLE
Delete Language button does not function more than once

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/app#203]
Steps to recreate:
1. Press Delete Language button
2. Do not type anything into the prompt
3. Press OK
4. Attempt to delete language again
5. Button will not trigger a prompt

Expected behavior: Language should not be deleted since user did not type 'YES', but the button should function for a second delete attempt.

The button does function on a page reset, so if the user navigates to the home page and back to the language page, or if the user selects another language in between delete attempts.

Tested on both Safari and Chrome.

**Comment by dwhieb** [comment]
‼
