### ISSUE TITLE
LanguageEditor: check validity on form before saving

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#218]
Check the validity of the LanguageEditor form before saving the language to the database. Don't save the language if the form is invalid; display errors instead (using `reportValidity()`, I think).

**Comment by vadekh** [comment]
For this issue, could I just add the following validity checker code lines to the `save()` method? 
`const form = this.el.querySelector('form');

    this.checkNameValidity();

    const isValid = form.checkValidity();

    form.reportValidity();

    if (!isValid) return;

**Comment by dwhieb** [comment]
@vadekh I was gonna say yes but this might be trickier than I thought. Say someone does this:

1. Edit field A, incorrectly.
2. Edit field B, correctly.
3. Fix field A.

We need to make sure the data in field B isn't prevented from saving because field A is incorrect.

If we want to validate the whole form at once, I think we'd need to add a Save button. Otherwise we'd have to validate each field individually using `input.checkValidity()`.

So our choices are:

autosave -> validate individual inputs
save button -> validate entire form (but save the user's work in a temporary place as they go)

Whichever choice we do here is how we should approach other pages too (especially the Lexeme Editor).

I think we should stick with the autosave approach and validate each individual input (with a debounce) for now, since that's what FLEx does and I'm modeling much of the behavior of Lotus after FLEx (because it's what so many linguists are already used to).

**Comment by vadekh** [comment]
Ok! I will keep the autosave functionality.

**Comment by vadekh** [comment]
@dwhieb I have noticed an issue related to this task:
This function in `LanguageEditor.js` :
```js
  handleFormUpdate(ev) {


    ev.preventDefault(); // prevent form from submitting data to the server


    const { name, value } = ev.target;
    const isAutonymUpdate = name.startsWith(`autonym`);
    const isNameUpdate    = name.startsWith(`name`);


    if (isAutonymUpdate) return this.updateAutonym(name, value);
    if (isNameUpdate) return this.updateName(name, value);
    return this.updateProperty(name, value);


  }
```
picks up events from the additional names handling. This results in `{name, value}` pairs that are incomplete, but are passed through the `updateProperty()` function. I do not think either of these functions should be handling additionalNames functionality. I can demo this for you in our session this week.

**Comment by dwhieb** [comment]
@vadekh nice catch. We can either add an additional guard for that (`isAdditionalNameUpdate`), or invert our logic so we're just attaching listeners directly to the simple text fields (Abbreviation, ISO, Glottocode). I think the latter would be the simpler and more maintable option at this point. If we do that, it'll probably obviate the `handleFormUpdate` method entirely.
