### ISSUE TITLE
nav components aren't keyboard navigable on Safari

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#228]
Both the main Nav and the LanguagesNav aren't keyboard navigable on Safari.

**Comment by vadekh** [comment]
@dwhieb Fixed! This was an issue on my end only, I did not have an accessibility setting turned on (of course set to off by default :/). Both lists are keyboard navigable now.

**Comment by dwhieb** [comment]
Huh, interesting! Didn't realize that was a feature. So the behavior we saw would be expected and actually a good thing in that case—if somebody doesn't want to use accessibility features like focus outlines and keyboard navigation, they shouldn't have to deal with it.
