### ISSUE TITLE
manage z-indexes

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#230]
Create a z-index.less file which tracks all the declared z-indexes in the project.

# Resource
https://www.smashingmagazine.com/2021/02/css-z-index-large-projects/?utm_source=pocket_mylist

**Comment by vadekh** [comment]
@dwhieb Hello! The HelpMenu component will have some z-indexes set so that the dropdown can be closed by clicking anywhere outside the menu.

**Comment by vadekh** [comment]
@dwhieb The z-indexes in the header element (first image) appear above the Banner element:

<img width="273" alt="Screen Shot 2021-10-05 at 11 13 53 AM" src="https://user-images.githubusercontent.com/36901345/136061890-712c66d9-016b-40e8-8e06-8e975e6421ca.png">

As well as the z-indexes in the `Nav.current` styling (second image):

<img width="275" alt="Screen Shot 2021-10-05 at 11 11 12 AM" src="https://user-images.githubusercontent.com/36901345/136061448-6efcb2db-0917-4c2e-a6d0-59f7b0a33e4e.png">

And lastly, the `::before` content for `.current` and the text of the current element itself when it is not highlighted via hover:

<img width="277" alt="Screen Shot 2021-10-05 at 11 10 59 AM" src="https://user-images.githubusercontent.com/36901345/136061562-43840697-0147-4326-9320-a9e57bd8e876.png">


Before fixing this, we should finalize the HelpMenu PR #293, and then manage/update all z-indexes. If we fix this before merging that PR, the functionality will likely break. The HelpMenu was also having a z-index conflict with the `header` element on the home page.

**Comment by vadekh** [comment]
Looks like the `current` class on `line-input` fields also needs to be pushed down below the banner with a z index.
