### ISSUE TITLE
styling for simple text fields

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#231]
Simple text fields should have a `.textline` class applied to them. This will apply to the abbreviation, Glottocode, and ISO fields. See the screenshot from the prototype below for the expected final look.

- [x] placeholder should be italicized
- [x] label (in the `<span>` should be bold and `font: smaller`)
- [x] help text should use the `.help-text` class (imported from `help-text.less`) and be wrapped in a `<p>` tag
- [x] the `<input>` should only have a light gray bottom border (use `border-bottom: var(--border)`)
- [x] when the container is wide enough that the label and the input/help text can fit beside each other (like in the prototype screenshot), they should be
- [x] when the container is too narrow for that, the label should appear above the input/help text (use flexbox for this and the previous point)

These styles should be encapsulated into a single `.textline` class. This class can just live inside of `LanguageEditor.less` for now, until we use it in another component.

Styling for the original prototype:
https://github.com/digitallinguistics/styles/tree/276068be8ec8e7f983b8c9e4ac9781e8f6eaf01d/components/forms/textline

![app](https://user-images.githubusercontent.com/5892997/90326837-bf6b1600-df52-11ea-8f1f-d8fc47c9441e.jpg)

**Comment by vadekh** [comment]
@dwhieb I've realized that the labels are not appearing Bolder than normal. I'm wondering if var(--bold) is not available in LanguageEditor.less

**Comment by dwhieb** [comment]
Might not be. The might be an old variable that was removed from either the app or the styles library. Check `variables.less` in both and see if it's there. If not, we can just use a regular `font-weight: bold;` declaration.

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [👨🏼‍💻 [app] review: .textline](https://trello.com/c/AWqMHJAf/663-%F0%9F%91%A8%F0%9F%8F%BC%F0%9F%92%BB-app-review-textline)
