### ISSUE TITLE
remove extraneous npm scripts

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#236]
Remove these scripts from `package.json` scripts field:

- [ ] `cypress-ct`
- [ ] `test:component`

**Comment by dwhieb** [comment]
@vadekh This is a super quick one if you feel like taking it.

**Comment by vadekh** [comment]
@dwhieb looks like this is handled in #240

**Comment by dwhieb** [comment]
@vadekh Awesome, closing now!
