### ISSUE TITLE
open issues to add Storybook stories for components that lack them

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#251]
Open issues to create Storybook stories for any components that lack them.

**Comment by vadekh** [comment]
@dwhieb This is done, I didn't create issues for the `BoxInput` and the `InputGroup` stories since they are done, just still in PR form. At least in the `components` directory. Are there any others that need this attention?

**Comment by dwhieb** [comment]
Thanks for tackling this @vadekh! Nope, I think that's it. If we catch others we can open issues for those later.
