### ISSUE TITLE
open issues to add tests for items that lack them

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#252]
Open issues to add tests for any components/modules that lack them, including `core/`, `models/`, and `utilities/`.

**Comment by vadekh** [comment]
- [x] Core
- [x] Models
- [x] Utilities
- [x] Components

**Comment by vadekh** [comment]
There are 2 untested files in `services/`. Should I open issues for them too? Otherwise this is done via #313 and #314

**Comment by dwhieb** [comment]
`Settings.js` needs a test suite but `DatabaseCollection.js` does not. `DatabaseCollection.js` is a submodule of the `Database.js` file. We could make this more explicit by doing this:

```
services/
  database.component.js
  database/
    index.js
    collection.js
```

This way it's clear that there's one test suite for the entire database module.

Alternatively we can add a dummy file like so:

```js
// DatabaseCollection.component.js
// This module is tested as part of the Database.js tests. No additional tests are needed for this file.
```

I think it'd be good to do one of these two things to document this. I'll let you pick.

**Comment by vadekh** [comment]
Done with #317

**Comment by dwhieb** [comment]
🙏🏼
