### ISSUE TITLE
update DLx JavaScript library to v0.3.0

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/app#253]
Specifically, we need a version of the library which includes `iso` and `glottolog` properties on the `Language` model.

- [x] Update DLx JavaScript library
- [x] Remove ISO Code code in `src/models/Language.js`

This will allow the testing data to be formatted correctly.

**Comment by vadekh** [comment]
@dwhieb did you do this when you reworked the Language model on my branch the other day?

**Comment by dwhieb** [comment]
I don't think so. The fix was actually app-specific, so didn't require updating the JS library. I did update to v3.1 in my Settings Page PR though (I think - I'm on my phone now and will check later). So I can close the v3.0 issue in that PR too if that's the case.

**Comment by vadekh** [comment]
I also updated in my PR now that I think about it so this will close with either one of the open PRs.
