### ISSUE TITLE
LanguageDropdown desynchronizes from LanguageList on new language add

### ISSUE THREAD

**Issue by Calvin1119** [digitallinguistics/app#259]
## Description

When a new language is added through the LanguageList, it doesn't cause the LanguageDropdown to reload. The new language will appear in the database and in the LanguageList, but not in the dropdown.

## Steps to Reproduce

Please list the steps to reproduce the behavior:

1. Go to the Language page
2. Click the add new language button

## Expected Behavior

The dropdown should update when the add language button is pressed

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[app] Languages Page: Add Language button](https://trello.com/c/Y6RBeFgc/11-app-languages-page-add-language-button)
