### ISSUE TITLE
Languages: clicking Add a Language adds two languages

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#264]
Clicking **Add a Language** inside the LanguagesNav adds 2 languages.

**To reproduce:**

1. Navigate to Languages page.
2. Navigate to Home page.
3. Navigate to Languages page again.
4. Click **Add a Language**.

This also seems to happen on the initial load of the Languages page.

**Comment by vadekh** [comment]
Yes I noticed this as well. Hadn't gotten around to opening an issue for it.
