### ISSUE TITLE
DLx Website link in main nav should display as an external link

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#297]
The "DLx Website" link in the main nav should display as an external link, with the icon after it.

This might be as easy as adding the `.link` class, but some extra work might need to be done to make sure the icon is displaying correctly too.

**Comment by vadekh** [comment]
@dwhieb just started working on this, but I realized that currently links to `digitallinguistics.io` are not considered external links in the styling. If that is the case, there is no need for this change, otherwise we will need to change a few other links.

**Comment by dwhieb** [comment]
Oh right, great point. I think we should update our external link check to be `app.digitallinguistics.io` instead of just `digitallinguistics.io` then. My intention with indicating the external links is to point out "hey if you click this you'll be leaving the app".

Would that change affect anything other than the Help Menu and Main Nav?

**Comment by vadekh** [comment]
I think there is one link on the Home Page as well.

**Comment by dwhieb** [comment]
Ok I'm fine with that being an external link too. Let's adjust `digitallinguistics.io` > `app.digitallinguistics.io` then.
