### ISSUE TITLE
after deleting an Additional Name, shift focus to "Add a language name" button

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#299]
After deleting an Additional Name, programmatically shift the focus to the "Add a language name" button.

**Comment by vadekh** [comment]
@dwhieb I dont think we need to do this. The current behavior leaves the focus where the deleted language name was, so a tab lands on the next name's edit button, and a Shift-tab lands on the add language name button. I remember a while back we discussed this and it match behavior of lists such as the tag list on GitHub. Closing this for now...

**Comment by dwhieb** [comment]
@vadekh I agree. I think the current behavior is the way to go.
