### ISSUE TITLE
use autocapitalize attribute

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#308]
The `autocapitalize` attribute tells browsers to autocapitalize or not autocapitalize text inside fields. We need to set this attribute on all of our inputs.

Here are the values to use for each field:

- [x] Language Name: `words`
- [x] Autonym: `words`
- [x] Additional Name > Name: `words`
- [x] Additional Name > Language: `words`
- [x] Note > Note Text: `sentences`
- [x] Note > Source: `off`

You can set this attribute directly on the `<input>` or `<textarea>` elements inside the HTML (`.hbs`) files, like so:

```html
<input autocapitalize=words>
```

Also check the JavaScript files for any places where we programmatically create an input.

# Reading

* https://www.htmhell.dev/tips/autocapitalization/?utm_source=CSS-Weekly&utm_campaign=Issue-475&utm_medium=web
* https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

**Comment by TongJ05** [comment]
closed by c02fbc03a6aa991f3925fc4b6104ab031e9acb10
