### ISSUE TITLE
review Tag component

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#320]
@vadekh I accidentally pushed a commit to `master` which had all my code for #319 in it. (I've updated the settings for the repo so this won't be possible in the future.) This issue is just for you to review those changes so you're aware of what I did:

https://github.com/digitallinguistics/app/compare/1cccad8751fbbf9ebca7125acd1d698ba916a69d...cbc52052ab5ccae45c2b4c4db1a212c17eace5f0

P.S. This was my first time building a custom HTML element with web components!

https://css-tricks.com/an-introduction-to-web-components/
https://www.webcomponents.org/introduction
https://developer.mozilla.org/en-US/docs/Web/Web_Components

**Comment by vadekh** [comment]
@dwhieb I looked through most of the new code in this repo and the javascript repo. I will explore the changes in browser etc next time I have time.
