### ISSUE TITLE
Language Editor: Orthographies

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#346]
Add an Orthographies section to the Language Editor, where the user can add/delete/edit the available orthographies for a language.

For now, each orthography will have these fields:

* name
* abbreviation
* notes

# Notes

- The name field is a MultiLangString and will need to use the MultiLangStringEditor view.
- Thinking about it more, this component actually _can_ have both a preview section and an editor, just like the Additional Names and Analysis Languages fields. In the preview, just display the orthography name in the default analysis language. The MultiLangString model has a `default` property you can use for this. So if `orthography.name` is a MultiLangString, you can call `orthography.name.default` to get the value to show in the preview.

**Comment by vadekh** [comment]
@dwhieb Is an orthography required for each language? I am assuming no based on the information in this issue so far, but I can change that if necessary.

**Comment by vadekh** [comment]
TODO:

- [ ] Use better test data, update tests, fixtures?
- [x] FIX: save on input update for name field
- [x] finish styling inputs
- [x] style preview spacing @ 50%
- [x] Implement MLSE for name input
- [x] Update preview to display with `default` as listed above
- [x] Implement defaults if needed (based on comment above)
- [x] Check type persistency

**Comment by dwhieb** [comment]
@vadekh At least one orthography is required for each language. When a new language is created, it should be given a single orthography object with these values:

* name: `Default`
* abbreviation: `default`

New languages are only created here:

https://github.com/digitallinguistics/app/blob/82da41ee7bd17c20d517ab04df3e310182cb5d1b/src/App/App.js#L62-L69
