### ISSUE TITLE
Settings page success alert with no file

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/app#360]
## Description

The Settings page broadcasts the message `Data imported successfully` when no file is selected.
<img width="790" alt="Screen Shot 2020-08-31 at 1 36 28 PM" src="https://user-images.githubusercontent.com/36901345/91754434-fe25e080-eb8e-11ea-9e9c-5c38d1ef37fb.png">

**Comment by vadekh** [comment]
Two possible fixes:
1) In `Settings.js` we check the length of `const files` before trying to import the data.
2) In `Database.js` we check that data exists before checking for a type property.

**Comment by dwhieb** [comment]
Good catch! I like option 1!
