### ISSUE TITLE
use monospace font for language codes / abbreviations

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#387]
Use the Fira Mono font for these fields in the Language Editor:

- [x] abbreviation
- [x] ISO 639-3
- [x] Glottocode

This can use a `.code` component.

**Comment by vadekh** [comment]
I think we should create a global component similar to the transcription component with an easy to apply class similar to `txn` that we can apply to these fields.

**Comment by dwhieb** [comment]
Good call!
