### ISSUE TITLE
Empty LanguageEditor Form renders with bad styling

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/app#398]
When there are no languages present in the app, the languages page incorrectly renders an empty language editor with incorrect styling (the form has no padding and the buttons are the full width).

The correct behavior should be that no form renders, just an `add a language` button.

**Comment by vadekh** [comment]
I can't recreate this at the moment, but I am hesitant to close it in case the issue does reappear. For now I won't do this one.

**Comment by dwhieb** [comment]
@vadekh Have you encountered this again? If not, let's close this. I can always reopen it if it resurfaces.

Can you grab a screenshot if the issue still persists?
