### ISSUE TITLE
Settings: content type of data export should be JSON rather than text

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#403]
In the Settings page, the exported data should have its content type set to `application/json`. Currently it downloads as a text file.

**Comment by vadekh** [comment]
@dwhieb This is fixed and can be closed I think.https://github.com/digitallinguistics/app/blob/3f5912c1fd15b5b58c41197442b50f18f5974456/src/app/App.js#L392

**Comment by dwhieb** [comment]
Closed by 5d094b925c395a3eb19c06a2c995eee0eacc4c04. (Thanks @vadekh!)
