### ISSUE TITLE
Settings: throws error before event listeners are added

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#404]
While the Settings page is rendering, it throws an error:

`TypeError: Cannot set property 'checked' of null`

The error is being thrown here:

https://github.com/digitallinguistics/app/blob/5d094b925c395a3eb19c06a2c995eee0eacc4c04/src/pages/Settings/Settings.js#L84

It looks like no value is being set for `app.settings.backupFrequency` when the app loads. It might be this was triggered after I cleared local storage, but this is something that we should anticipate the user doing (if they clear the page cache).

## Current Workaround
1. Open the console.
1. Enter `app.settings.backupFrequency = 'daily'`
1. Reload the page

**Comment by vadekh** [comment]
@dwhieb I've had this error too but I restarted the process and it disappeared so I though it was just on my environment.

**Comment by vadekh** [comment]
@dwhieb Not sure if you can still recreate this issue, I cannot. I believe the implementation of `App.defaultSettings` should always set the `backupFrequency` to `daily` the first time the app loads, even after a cleared cache.

**Comment by dwhieb** [comment]
Closed by 5d094b925c395a3eb19c06a2c995eee0eacc4c04.
