### ISSUE TITLE
Additional Name should update its own model

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#409]
Currently, the Language Editor does the work of updating `language.additionalNames` whenever the user edits an additional name.

Instead, the Additional Name component should update the name object directly. The Language Editor should then listen for a click event on any Additional Names "Save" button, and save the Language model.

The `LanguageEditor#updateAdditionalNames()` method will no longer be necessary:

https://github.com/digitallinguistics/app/blob/bd4e8c2e17c2d8fcd4da50593542a8a8f5cf1553/src/pages/Languages/LanguageEditor/LanguageEditor.js#L186-L203

h/t @vadekh for catching the code smell

**Comment by vadekh** [comment]
Also update Notes saving issue
