### ISSUE TITLE
test: Node version should match version in package.json

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/app#73]
We should have a test that checks that the developer is using the correct major version of Node when building the project.

* Create a test to check that the running Node version matches the version in `package.json`.
* This will be a unit test with Mocha rather than an integration test with Cypress.
* The test should live in `test/node-version.test.js`.
* The test should only be concerned with the _major_ version, not the minor or patch version.
* Use the [semver](https://www.npmjs.com/package/semver) package for reliable version comparisons.

**Comment by vadekh** [comment]
@dwhieb Actually it occurred to me that any version >=16 should pass this test, I will adjust the test tomorrow to accommodate that...
